import type { RuleDefinition } from '../../types'

export const RESTAURANT_PROFILE_ID = 'restaurant'

export const RESTAURANT_RULES: RuleDefinition[] = [
  {
    id:             'MENU_ITEMS_COUNT',
    profile:        RESTAURANT_PROFILE_ID,
    category:       'CONTENT',
    title:          'Menu has items',
    description:    'At least 5 menu items must be created and visible to customers.',
    weight:         12,
    required:       true,
    enabled:        true,
    evaluationType: 'NUMBER',
    expectedValue:  5,
  },
  {
    id:             'MENU_CATEGORIES',
    profile:        RESTAURANT_PROFILE_ID,
    category:       'CONTENT',
    title:          'Menu has categories',
    description:    'At least 2 menu categories must be configured.',
    weight:         8,
    required:       true,
    enabled:        true,
    evaluationType: 'NUMBER',
    expectedValue:  2,
  },
  {
    id:             'TABLES_CONFIGURED',
    profile:        RESTAURANT_PROFILE_ID,
    category:       'SETUP',
    title:          'Tables configured',
    description:    'At least 1 table must be set up for dine-in service.',
    weight:         10,
    required:       true,
    enabled:        true,
    evaluationType: 'NUMBER',
    expectedValue:  1,
  },
  {
    id:             'STAFF_REGISTERED',
    profile:        RESTAURANT_PROFILE_ID,
    category:       'SETUP',
    title:          'Staff registered',
    description:    'At least 1 staff member must be registered (excluding owner).',
    weight:         10,
    required:       true,
    enabled:        true,
    evaluationType: 'NUMBER',
    expectedValue:  1,
  },
  {
    id:             'BILLING_ACTIVE',
    profile:        RESTAURANT_PROFILE_ID,
    category:       'COMPLIANCE',
    title:          'Billing active',
    description:    'Billing status must be COLLECTING_DEBT or GRACE_PERIOD (not SUSPENDED).',
    weight:         20,
    required:       true,
    enabled:        true,
    evaluationType: 'BOOLEAN',
    expectedValue:  true,
  },
  {
    id:             'ORDERS_LAST_30_DAYS',
    profile:        RESTAURANT_PROFILE_ID,
    category:       'ACTIVITY',
    title:          'Active orders in last 30 days',
    description:    'At least 10 completed orders in the last 30 days.',
    weight:         20,
    required:       false,
    enabled:        true,
    evaluationType: 'NUMBER',
    expectedValue:  10,
  },
  {
    id:             'WEEKLY_ORDER_VOLUME',
    profile:        RESTAURANT_PROFILE_ID,
    category:       'ACTIVITY',
    title:          'Weekly order volume',
    description:    'Weekly order average of at least 20 orders.',
    weight:         10,
    required:       false,
    enabled:        true,
    evaluationType: 'NUMBER',
    expectedValue:  20,
  },
  {
    id:             'QR_ORDERS_ENABLED',
    profile:        RESTAURANT_PROFILE_ID,
    category:       'FEATURES',
    title:          'QR ordering enabled',
    description:    'At least 1 QR code order received in last 30 days.',
    weight:         10,
    required:       false,
    enabled:        true,
    evaluationType: 'BOOLEAN',
    expectedValue:  true,
  },
  {
    id:             'RESERVATIONS_ACTIVE',
    profile:        RESTAURANT_PROFILE_ID,
    category:       'FEATURES',
    title:          'Reservations active',
    description:    'At least 1 reservation recorded in the last 30 days.',
    weight:         8,
    required:       false,
    enabled:        true,
    evaluationType: 'BOOLEAN',
    expectedValue:  true,
  },
  {
    id:             'MARKETING_CONFIGURED',
    profile:        RESTAURANT_PROFILE_ID,
    category:       'MARKETING',
    title:          'Marketing configured',
    description:    'At least 1 marketing generation completed for this tenant.',
    weight:         8,
    required:       false,
    enabled:        true,
    evaluationType: 'BOOLEAN',
    expectedValue:  true,
  },
  {
    id:             'LOYALTY_CUSTOMERS',
    profile:        RESTAURANT_PROFILE_ID,
    category:       'ENGAGEMENT',
    title:          'Loyalty customers',
    description:    'At least 1 loyalty customer opted in.',
    weight:         5,
    required:       false,
    enabled:        true,
    evaluationType: 'BOOLEAN',
    expectedValue:  true,
  },
  {
    id:             'INVENTORY_ACTIVE',
    profile:        RESTAURANT_PROFILE_ID,
    category:       'FEATURES',
    title:          'Smart Inventory active',
    description:    'Smart Inventory module has been enabled for this tenant.',
    weight:         5,
    required:       false,
    enabled:        true,
    evaluationType: 'BOOLEAN',
    expectedValue:  true,
  },
]
