/**
 * Seed data for buyer personas.
 * business_types and countries are referenced by slug/code at seed time
 * and resolved to ObjectIds by the seed runner.
 */
export const PERSONAS = [
  {
    slug: 'traditional_owner',
    nameEn: 'Traditional Owner',
    nameAr: 'صاحب المحل التقليدي',
    nameFr: 'Patron Traditionnel',
    descriptionEn: 'A 40–60 year-old restaurant owner who has run their business for years without technology. Skeptical of digital tools but open to solutions that "just work".',
    painPoints: [
      'Afraid of losing control over operations',
      'No time to learn new software',
      'Bad past experience with tech vendors',
      'Cash-flow unpredictability',
    ],
    goals: [
      'Keep the restaurant profitable',
      'Reduce order errors',
      'Have more time for family',
    ],
    businessTypeSlugs: ['restaurant', 'cafe'],
    countryCodes:      ['MA', 'TN', 'DZ', 'EG'],
    demographic: {
      ageRange:          { min: 40, max: 65 },
      techSavviness:     'LOW',
      decisionStyle:     'EMOTIONAL',
      preferredChannels: ['WHATSAPP', 'PHONE'],
    },
    sortOrder: 1,
    isActive:  true,
  },
  {
    slug: 'young_entrepreneur',
    nameEn: 'Young Entrepreneur',
    nameAr: 'رائد الأعمال الشاب',
    nameFr: 'Jeune Entrepreneur',
    descriptionEn: 'A 25–35 year-old who recently opened their first café or food concept. Tech-savvy, Instagram-focused, and growth-oriented. Wants to scale fast.',
    painPoints: [
      'Limited budget',
      'Managing a young team',
      'Inconsistent customer flow',
      'Competing with established brands',
    ],
    goals: [
      'Build a loyal customer base',
      'Grow via social media',
      'Open a second location within 2 years',
    ],
    businessTypeSlugs: ['cafe', 'food_truck', 'bakery', 'juice_bar'],
    countryCodes:      ['MA', 'SA', 'AE', 'TN', 'FR'],
    demographic: {
      ageRange:          { min: 22, max: 38 },
      techSavviness:     'HIGH',
      decisionStyle:     'IMPULSIVE',
      preferredChannels: ['WHATSAPP', 'EMAIL', 'IN_APP'],
    },
    sortOrder: 2,
    isActive:  true,
  },
  {
    slug: 'multi_branch_manager',
    nameEn: 'Multi-Branch Manager',
    nameAr: 'مدير فروع متعددة',
    nameFr: 'Gérant Multi-Établissements',
    descriptionEn: 'Manages 3–10 restaurant branches. Analytical, ROI-driven, and comfortable with SaaS tools. Needs consolidated reporting and staff management across locations.',
    painPoints: [
      'No visibility across branches',
      'Staff performance inconsistency',
      'Inventory waste at scale',
      'Complex payroll across branches',
    ],
    goals: [
      'Real-time cross-branch analytics',
      'Standardize operations',
      'Reduce food cost by 10%',
    ],
    businessTypeSlugs: ['restaurant', 'cafe', 'fast_food'],
    countryCodes:      ['MA', 'SA', 'AE', 'KW', 'QA'],
    demographic: {
      ageRange:          { min: 30, max: 55 },
      techSavviness:     'HIGH',
      decisionStyle:     'ANALYTICAL',
      preferredChannels: ['EMAIL', 'WHATSAPP'],
    },
    sortOrder: 3,
    isActive:  true,
  },
  {
    slug: 'hotel_food_manager',
    nameEn: 'Hotel Food & Beverage Manager',
    nameAr: 'مدير الأغذية والمشروبات بالفندق',
    nameFr: 'Directeur F&B Hôtelier',
    descriptionEn: 'Manages restaurant and bar operations within a hotel. Has corporate approval processes and focuses on guest experience scores.',
    painPoints: [
      'Complex service flows (room service, restaurant, banquets)',
      'Guest complaint resolution',
      'Integration with hotel PMS',
      'Seasonal demand spikes',
    ],
    goals: [
      'Improve guest satisfaction scores',
      'Reduce food waste',
      'Streamline event catering',
    ],
    businessTypeSlugs: ['hotel'],
    countryCodes:      ['MA', 'SA', 'AE', 'TN', 'EG'],
    demographic: {
      ageRange:          { min: 30, max: 50 },
      techSavviness:     'MEDIUM',
      decisionStyle:     'ANALYTICAL',
      preferredChannels: ['EMAIL', 'PHONE'],
    },
    sortOrder: 4,
    isActive:  true,
  },
  {
    slug: 'traiteur_owner',
    nameEn: 'Catering Owner',
    nameAr: 'صاحب شركة تموين',
    nameFr: 'Propriétaire Traiteur',
    descriptionEn: 'Runs a catering/traiteur business focused on events (weddings, corporate). Revenue is project-based and highly seasonal.',
    painPoints: [
      'Guest list management for large events',
      'Scaling production for 500+ guests',
      'Collecting deposits and managing payments',
      'Coordinating kitchen + delivery teams',
    ],
    goals: [
      'Book more events',
      'Automate guest communication',
      'Reduce per-event logistics overhead',
    ],
    businessTypeSlugs: ['caterer'],
    countryCodes:      ['MA', 'TN', 'DZ', 'FR', 'SA'],
    demographic: {
      ageRange:          { min: 30, max: 55 },
      techSavviness:     'MEDIUM',
      decisionStyle:     'SOCIAL',
      preferredChannels: ['WHATSAPP', 'PHONE'],
    },
    sortOrder: 5,
    isActive:  true,
  },
]
