/**
 * Seed data for marketing scenarios.
 * persona slugs and businessType slugs are resolved to ObjectIds at seed time.
 */
export const SCENARIOS = [
  // ── AWARENESS ──────────────────────────────────────────────────────────────
  {
    slug:          'demo_request_submitted',
    stage:         'AWARENESS',
    trigger:       'demo_request_submitted',
    nameEn:        'Demo Request Submitted',
    nameAr:        'طلب تجربة مجانية',
    nameFr:        'Demande de Démo Soumise',
    descriptionEn: 'Prospect just submitted the demo request form. First contact within minutes.',
    personaSlugs:  [],   // all personas
    businessTypeSlugs: [],
    priority:      100,
    isActive:      true,
  },
  {
    slug:          'landing_page_visit_no_action',
    stage:         'AWARENESS',
    trigger:       'lead_captured_no_signup',
    nameEn:        'Visited Landing, No Signup',
    nameAr:        'زار الصفحة ولم يسجل',
    nameFr:        'Visite Sans Inscription',
    descriptionEn: 'Prospect visited the landing page and left without signing up.',
    personaSlugs:  ['traditional_owner', 'young_entrepreneur'],
    businessTypeSlugs: [],
    priority:      60,
    isActive:      true,
  },
  // ── CONSIDERATION ──────────────────────────────────────────────────────────
  {
    slug:          'trial_day_1',
    stage:         'CONSIDERATION',
    trigger:       'signup_completed',
    nameEn:        'Trial Day 1 — Welcome',
    nameAr:        'اليوم الأول من التجربة — مرحباً',
    nameFr:        'Jour 1 de Période d\'Essai — Bienvenue',
    descriptionEn: 'Account just created. Guide the user through first setup.',
    personaSlugs:  [],
    businessTypeSlugs: [],
    priority:      100,
    isActive:      true,
  },
  {
    slug:          'trial_day_3_no_menu',
    stage:         'CONSIDERATION',
    trigger:       'trial_day_3_no_menu_created',
    nameEn:        'Trial Day 3 — No Menu Created',
    nameAr:        'اليوم الثالث — لم ينشئ قائمة طعام',
    nameFr:        'Jour 3 — Aucun Menu Créé',
    descriptionEn: 'User signed up 3 days ago but hasn\'t created any menu items yet.',
    personaSlugs:  ['traditional_owner'],
    businessTypeSlugs: [],
    priority:      90,
    isActive:      true,
  },
  {
    slug:          'trial_day_5_menu_no_qr',
    stage:         'CONSIDERATION',
    trigger:       'trial_day_5_menu_created_no_qr_scan',
    nameEn:        'Trial Day 5 — Menu Done, No QR Scan',
    nameAr:        'اليوم الخامس — القائمة جاهزة لكن لا مسح QR',
    nameFr:        'Jour 5 — Menu Prêt, Aucun Scan QR',
    descriptionEn: 'User built the menu but never printed/scanned QR codes — real value not yet felt.',
    personaSlugs:  [],
    businessTypeSlugs: [],
    priority:      85,
    isActive:      true,
  },
  // ── DECISION ───────────────────────────────────────────────────────────────
  {
    slug:          'trial_day_6_expiry_tomorrow',
    stage:         'DECISION',
    trigger:       'trial_ends_in_24h',
    nameEn:        'Trial Expires Tomorrow',
    nameAr:        'تنتهي التجربة غداً',
    nameFr:        'Essai Expire Demain',
    descriptionEn: 'Trial ends in 24 hours. Urgency push to convert.',
    personaSlugs:  [],
    businessTypeSlugs: [],
    priority:      100,
    isActive:      true,
  },
  {
    slug:          'trial_expired_no_payment',
    stage:         'DECISION',
    trigger:       'trial_expired_balance_negative',
    nameEn:        'Trial Expired — Balance Negative',
    nameAr:        'انتهت التجربة — الرصيد سلبي',
    nameFr:        'Essai Expiré — Solde Négatif',
    descriptionEn: 'Trial over, wallet balance negative. Debt detection triggered PAST_DUE.',
    personaSlugs:  [],
    businessTypeSlugs: [],
    priority:      100,
    isActive:      true,
  },
  // ── ONBOARDING ─────────────────────────────────────────────────────────────
  {
    slug:          'first_real_order',
    stage:         'ONBOARDING',
    trigger:       'first_order_from_qr_menu',
    nameEn:        'First Real Order Received',
    nameAr:        'أول طلب حقيقي',
    nameFr:        'Première Vraie Commande',
    descriptionEn: 'The restaurant just received its first QR order from a real customer. Celebrate and guide next steps.',
    personaSlugs:  [],
    businessTypeSlugs: [],
    priority:      90,
    isActive:      true,
  },
  // ── RETENTION ──────────────────────────────────────────────────────────────
  {
    slug:          'no_order_7_days',
    stage:         'RETENTION',
    trigger:       'no_order_in_7_days',
    nameEn:        'No Order in 7 Days',
    nameAr:        'لا طلبات منذ 7 أيام',
    nameFr:        '7 Jours Sans Commande',
    descriptionEn: 'Active account but no orders for 7 days. May have a problem or using competitors.',
    personaSlugs:  [],
    businessTypeSlugs: [],
    priority:      70,
    isActive:      true,
  },
  {
    slug:          'monthly_review_active',
    stage:         'RETENTION',
    trigger:       'monthly_health_check',
    nameEn:        'Monthly Review — Active Account',
    nameAr:        'المراجعة الشهرية — حساب نشط',
    nameFr:        'Bilan Mensuel — Compte Actif',
    descriptionEn: 'Monthly check-in for happy active accounts. Share their stats, suggest feature upgrades.',
    personaSlugs:  [],
    businessTypeSlugs: [],
    priority:      50,
    isActive:      true,
  },
  // ── REACTIVATION ───────────────────────────────────────────────────────────
  {
    slug:          'suspended_account_reactivation',
    stage:         'REACTIVATION',
    trigger:       'account_suspended_payment_overdue',
    nameEn:        'Suspended Account — Payment Overdue',
    nameAr:        'حساب موقوف — متأخر في الدفع',
    nameFr:        'Compte Suspendu — Paiement En Retard',
    descriptionEn: 'Account suspended after grace period. Final attempt to recover revenue.',
    personaSlugs:  [],
    businessTypeSlugs: [],
    priority:      100,
    isActive:      true,
  },
  {
    slug:          'cold_lead_30_days',
    stage:         'REACTIVATION',
    trigger:       'lead_no_signup_30_days',
    nameEn:        'Cold Lead — 30 Days Inactive',
    nameAr:        'عميل محتمل بارد — 30 يوماً',
    nameFr:        'Lead Froid — 30 Jours d\'Inactivité',
    descriptionEn: 'Demo request submitted 30 days ago but never signed up. Last reactivation attempt.',
    personaSlugs:  ['traditional_owner', 'young_entrepreneur'],
    businessTypeSlugs: [],
    priority:      60,
    isActive:      true,
  },
]
