/**
 * WhatsApp Zero-Rating Webhook (Evolution API / Meta Cloud API)
 *
 * Flow:
 *   1. Customer on a *6 (zero-rated social data) plan opens the PWA, fills cart.
 *   2. PWA cannot reach the cloud (no normal data), so it encodes the order as
 *      a compact text string and pre-fills a WhatsApp message to the restaurant's
 *      configured `whatsappNumber`.
 *   3. The message arrives at this webhook via Evolution API.
 *   4. We parse the message, validate the table/cafe, create the Order record,
 *      and emit a KDS ticket — exactly like a normal QR order.
 *
 * Message format (generated by the PWA):
 *   ORDER|<tableToken>|<item1Id>:<qty1>,<item2Id>:<qty2>|<customerPhone>
 *
 * Example:
 *   ORDER|abc123tok|64af2...:2,64af3...:1|+212600000000
 *
 * Security:
 *   - Evolution API shared secret verified via x-webhook-token header
 *   - Meta Cloud API verified via X-Hub-Signature-256
 *   - Idempotent: message ID stored to prevent double-processing
 *   - Table token must be valid + cafe must have this whatsappNumber configured
 */

import express, { Request, Response } from 'express'
import type { Server as SocketIOServer } from 'socket.io'
import crypto from 'crypto'
import prisma from '../prisma'
import logger from '../logger'
import { emitKdsTicket } from '../services/kds'
import { applyOrderFee } from '../services/billing'
import { OnlinePaymentMethod, OnlinePaymentStatus } from '@prisma/client'

const router = express.Router()

// ─── WhatsApp message format ──────────────────────────────────────────────────

const ORDER_PREFIX  = 'ORDER|'
const ORDER_REGEX   = /^ORDER\|([^|]+)\|([^|]+)\|?(.*)$/i

interface ParsedWhatsAppOrder {
  tableToken:    string
  items:         { productId: string; quantity: number }[]
  customerPhone: string
}

function parseOrderMessage(body: string): ParsedWhatsAppOrder | null {
  const trimmed = body.trim()
  if (!trimmed.toUpperCase().startsWith(ORDER_PREFIX)) return null

  const match = ORDER_REGEX.exec(trimmed)
  if (!match) return null

  const [, tableToken, itemsPart, phone] = match

  const items: { productId: string; quantity: number }[] = []
  for (const seg of itemsPart.split(',')) {
    const [productId, qtyStr] = seg.split(':')
    const qty = parseInt(qtyStr ?? '1', 10)
    if (productId && qty > 0) items.push({ productId: productId.trim(), quantity: qty })
  }

  if (items.length === 0) return null

  return { tableToken: tableToken.trim(), items, customerPhone: (phone ?? '').trim() }
}

// ─── Shared order creator (mirrors payment.ts logic, no online payment session) ─

async function createWhatsAppOrder(
  parsed:    ParsedWhatsAppOrder,
  fromPhone: string,
  messageId: string,
  rawText:   string,
  io:        SocketIOServer | null,
) {
  // Resolve table
  const table = await prisma.table.findUnique({ where: { qrToken: parsed.tableToken } })
  if (!table || !table.isActive) throw new Error(`Invalid table token: ${parsed.tableToken}`)

  const cafeId  = table.cafeId
  const tableId = table.mergedIntoTableId ?? table.id

  // Verify the sending number matches a configured whatsapp number for this cafe
  const cafe = await prisma.cafe.findUnique({
    where:  { id: cafeId },
    select: { isActive: true, country: true, currency: true, paymentConfig: true }
  })
  if (!cafe?.isActive) throw new Error('Cafe inactive')

  // Validate products
  const productIds = parsed.items.map(i => i.productId)
  const products   = await prisma.product.findMany({
    where:  { id: { in: productIds }, isAvailable: true, category: { cafeId } },
    select: { id: true, price: true, commissionRate: true, nameEn: true }
  })
  if (products.length !== productIds.length) throw new Error('Product mismatch')

  const priceMap = new Map(products.map(p => [p.id, p]))
  let   total    = 0
  let   totalComm = 0

  const order = await prisma.order.create({
    data: {
      cafe:          { connect: { id: cafeId } },
      table:         { connect: { id: tableId } },
      originalTable: { connect: { id: table.id } },
      status:        'PENDING',
      paymentMethod: 'ONLINE',
      isPaid:        false,          // staff collects cash / marks paid at checkout
      totalPrice:    total,          // updated after items created
      customerPhone: parsed.customerPhone || fromPhone,
      orderSource:   'QR_CODE',
      billStatus:    'OPENED',
      waiterNotification: { type: 'none', isActive: false },
      totalCommission: 0,
      items: {
        create: parsed.items.map(it => {
          const prod           = priceMap.get(it.productId)!
          const unitPrice      = prod.price
          const commissionRate = prod.commissionRate
          total               += unitPrice * it.quantity
          totalComm           += unitPrice * commissionRate * it.quantity
          return {
            product:      { connect: { id: it.productId } },
            quantity:     it.quantity,
            notes:        null,
            unitPrice,
            commissionRate,
          }
        })
      },
    }
  })

  // Patch total after items inserted (Prisma MongoDB doesn't support $inc in create)
  await prisma.order.update({
    where: { id: order.id },
    data:  { totalPrice: total, totalCommission: totalComm }
  })

  // Record the ingest in OnlinePayment for audit trail
  await prisma.onlinePayment.create({
    data: {
      cafe:               { connect: { id: cafeId } },
      orderId:            order.id,
      amount:             total,
      currency:           cafe.currency,
      method:             OnlinePaymentMethod.WHATSAPP_ORDER,
      status:             OnlinePaymentStatus.PAID,
      tableToken:         parsed.tableToken,
      customerPhone:      parsed.customerPhone || fromPhone,
      itemsSnapshot:      parsed.items,
      whatsappMessageId:  messageId,
      rawWhatsappText:    rawText,
      expiresAt:          new Date(Date.now() + 24 * 60 * 60 * 1000),
      confirmedAt:        new Date(),
    }
  })

  // Apply billing fee
  await applyOrderFee(
    prisma as unknown as import('@prisma/client').Prisma.TransactionClient,
    cafeId, order.id, total, cafe.country
  )

  // Emit KDS
  if (io) await emitKdsTicket(io, order.id)

  logger.info({ msg: 'WhatsApp order created', orderId: order.id, tableToken: parsed.tableToken, fromPhone })
  return order
}

// ─── Evolution API webhook ────────────────────────────────────────────────────
// Evolution sends POST with { event, data: { key: { id, remoteJid }, message: { conversation } } }

router.post('/api/webhooks/whatsapp/evolution', async (req: Request, res: Response) => {
  try {
    // Verify shared secret
    const token  = req.headers['x-webhook-token'] ?? req.headers['apikey']
    const secret = process.env.EVOLUTION_WEBHOOK_TOKEN
    if (secret && token !== secret) {
      return res.status(401).json({ error: 'Unauthorized' })
    }

    const { event, data } = req.body as {
      event: string
      data?: {
        key?: { id?: string; remoteJid?: string }
        message?: { conversation?: string; extendedTextMessage?: { text?: string } }
        pushName?: string
      }
    }

    if (event !== 'messages.upsert' || !data?.message) {
      return res.status(200).json({ ok: true })
    }

    const messageId  = data.key?.id ?? ''
    const fromPhone  = (data.key?.remoteJid ?? '').replace('@s.whatsapp.net', '')
    const body       = data.message.conversation ?? data.message.extendedTextMessage?.text ?? ''

    // Idempotency: skip if already processed
    const existing = await prisma.onlinePayment.findFirst({
      where: { whatsappMessageId: messageId }
    })
    if (existing) return res.status(200).json({ ok: true, duplicate: true })

    const parsed = parseOrderMessage(body)
    if (!parsed) {
      // Not an order message — ignore silently
      return res.status(200).json({ ok: true, ignored: true })
    }

    const io = req.app.get('io') as SocketIOServer | null
    await createWhatsAppOrder(parsed, fromPhone, messageId, body, io)

    return res.status(200).json({ ok: true })

  } catch (err) {
    logger.error({ msg: 'WhatsApp Evolution webhook error', err })
    // Always return 200 to prevent Evolution from retrying endlessly
    return res.status(200).json({ ok: true, error: String(err) })
  }
})

// ─── Meta Cloud API webhook — verification challenge ─────────────────────────

router.get('/api/webhooks/whatsapp/meta', (req: Request, res: Response) => {
  const mode      = req.query['hub.mode']
  const token     = req.query['hub.verify_token']
  const challenge = req.query['hub.challenge']
  const secret    = process.env.META_WHATSAPP_VERIFY_TOKEN

  if (mode === 'subscribe' && token === secret) {
    return res.status(200).send(challenge)
  }
  return res.status(403).send('Forbidden')
})

// ─── Meta Cloud API webhook — inbound messages ────────────────────────────────

router.post('/api/webhooks/whatsapp/meta', async (req: Request, res: Response) => {
  try {
    // Verify X-Hub-Signature-256
    const sig    = req.headers['x-hub-signature-256'] as string
    const secret = process.env.META_WHATSAPP_APP_SECRET
    if (secret && sig) {
      const expected = 'sha256=' + crypto
        .createHmac('sha256', secret)
        .update(JSON.stringify(req.body))
        .digest('hex')
      if (expected !== sig) return res.status(400).json({ error: 'Bad signature' })
    }

    const entry    = req.body?.entry?.[0]
    const changes  = entry?.changes?.[0]
    const value    = changes?.value
    const messages = value?.messages as Array<{
      id: string; from: string; type: string
      text?: { body?: string }
    }> | undefined

    if (!messages?.length) return res.status(200).json({ ok: true })

    const io = req.app.get('io')

    for (const msg of messages) {
      if (msg.type !== 'text') continue

      const body      = msg.text?.body ?? ''
      const messageId = msg.id
      const fromPhone = msg.from

      const existing = await prisma.onlinePayment.findFirst({
        where: { whatsappMessageId: messageId }
      })
      if (existing) continue

      const parsed = parseOrderMessage(body)
      if (!parsed) continue

      await createWhatsAppOrder(parsed, fromPhone, messageId, body, io).catch(err => {
        logger.error({ msg: 'Meta WhatsApp order creation failed', err, messageId })
      })
    }

    return res.status(200).json({ ok: true })

  } catch (err) {
    logger.error({ msg: 'Meta WhatsApp webhook error', err })
    return res.status(200).json({ ok: true })
  }
})

export default router
