/**
 * WhatsApp Zero-Rating Webhook — Evolution API only
 *
 * Flow:
 *   1. Customer on a *6 (zero-rated social data) plan opens the PWA, fills cart.
 *   2. PWA cannot reach the cloud, so it encodes the order as a compact text
 *      string and pre-fills a WhatsApp message to the restaurant's whatsappNumber.
 *   3. The message arrives here via Evolution API POST.
 *   4. We parse it, validate the table/cafe, create the Order, emit a KDS ticket.
 *
 * Message format (generated by the PWA):
 *   ORDER|<tableToken>|<productId>:<qty>,<productId>:<qty>|<customerPhone>
 *
 * Example:
 *   ORDER|abc123tok|64af2...:2,64af3...:1|+212600000000
 *
 * Security:
 *   - Shared secret verified via x-webhook-token (or apikey) header
 *   - Idempotent: message ID stored to prevent double-processing
 */

import express, { Request, Response } from 'express'
import type { Server as SocketIOServer } from 'socket.io'
import prisma from '../prisma'
import logger from '../logger'
import { emitKdsTicket } from '../services/kds'
import { applyOrderFee } from '../services/billing'
import { OnlinePaymentMethod, OnlinePaymentStatus } from '@prisma/client'

const router = express.Router()

// ─── Message parser ───────────────────────────────────────────────────────────

const ORDER_PREFIX = 'ORDER|'
const ORDER_REGEX  = /^ORDER\|([^|]+)\|([^|]+)\|?(.*)$/i

interface ParsedOrder {
  tableToken:    string
  items:         { productId: string; quantity: number }[]
  customerPhone: string
}

function parseOrderMessage(body: string): ParsedOrder | null {
  const trimmed = body.trim()
  if (!trimmed.toUpperCase().startsWith(ORDER_PREFIX)) return null

  const match = ORDER_REGEX.exec(trimmed)
  if (!match) return null

  const [, tableToken, itemsPart, phone] = match

  const items: { productId: string; quantity: number }[] = []
  for (const seg of itemsPart.split(',')) {
    const [productId, qtyStr] = seg.split(':')
    const qty = parseInt(qtyStr ?? '1', 10)
    if (productId && qty > 0) items.push({ productId: productId.trim(), quantity: qty })
  }

  if (items.length === 0) return null
  return { tableToken: tableToken.trim(), items, customerPhone: (phone ?? '').trim() }
}

// ─── Order creator ────────────────────────────────────────────────────────────

async function createWhatsAppOrder(
  parsed:    ParsedOrder,
  fromPhone: string,
  messageId: string,
  rawText:   string,
  io:        SocketIOServer | null,
) {
  const table = await prisma.table.findUnique({ where: { qrToken: parsed.tableToken } })
  if (!table || !table.isActive) throw new Error(`Invalid table token: ${parsed.tableToken}`)

  const cafeId  = table.cafeId
  const tableId = table.mergedIntoTableId ?? table.id

  const cafe = await prisma.cafe.findUnique({
    where:  { id: cafeId },
    select: { isActive: true, country: true, currency: true }
  })
  if (!cafe?.isActive) throw new Error('Cafe inactive')

  const productIds = parsed.items.map(i => i.productId)
  const products   = await prisma.product.findMany({
    where:  { id: { in: productIds }, isAvailable: true, category: { cafeId } },
    select: { id: true, price: true, commissionRate: true }
  })
  if (products.length !== productIds.length) throw new Error('Product mismatch')

  const priceMap = new Map(products.map(p => [p.id, p]))
  let   total    = 0
  let   totalComm = 0

  const order = await prisma.order.create({
    data: {
      cafe:          { connect: { id: cafeId } },
      table:         { connect: { id: tableId } },
      originalTable: { connect: { id: table.id } },
      status:        'PENDING',
      paymentMethod: 'ONLINE',
      isPaid:        false,
      totalPrice:    0,
      customerPhone: parsed.customerPhone || fromPhone,
      orderSource:   'QR_CODE',
      billStatus:    'OPENED',
      waiterNotification: { type: 'none', isActive: false },
      totalCommission: 0,
      items: {
        create: parsed.items.map(it => {
          const prod           = priceMap.get(it.productId)!
          const unitPrice      = prod.price
          const commissionRate = prod.commissionRate
          total               += unitPrice * it.quantity
          totalComm           += unitPrice * commissionRate * it.quantity
          return {
            product:      { connect: { id: it.productId } },
            quantity:     it.quantity,
            notes:        null,
            unitPrice,
            commissionRate,
          }
        })
      },
    }
  })

  await prisma.order.update({
    where: { id: order.id },
    data:  { totalPrice: total, totalCommission: totalComm }
  })

  await prisma.onlinePayment.create({
    data: {
      cafe:               { connect: { id: cafeId } },
      orderId:            order.id,
      amount:             total,
      currency:           cafe.currency,
      method:             OnlinePaymentMethod.WHATSAPP_ORDER,
      status:             OnlinePaymentStatus.PAID,
      tableToken:         parsed.tableToken,
      customerPhone:      parsed.customerPhone || fromPhone,
      itemsSnapshot:      parsed.items,
      whatsappMessageId:  messageId,
      rawWhatsappText:    rawText,
      expiresAt:          new Date(Date.now() + 24 * 60 * 60 * 1000),
      confirmedAt:        new Date(),
    }
  })

  await applyOrderFee(
    prisma as unknown as import('@prisma/client').Prisma.TransactionClient,
    cafeId, order.id, total, cafe.country, false, parsed.items.length
  )

  if (io) await emitKdsTicket(io, order.id)

  logger.info({ msg: 'WhatsApp order created', orderId: order.id, tableToken: parsed.tableToken, fromPhone })
  return order
}

// ─── Evolution API webhook ────────────────────────────────────────────────────

router.post('/api/webhooks/whatsapp/evolution', async (req: Request, res: Response) => {
  try {
    const token  = req.headers['x-webhook-token'] ?? req.headers['apikey']
    const secret = process.env.EVOLUTION_WEBHOOK_TOKEN
    if (secret && token !== secret) {
      return res.status(401).json({ error: 'Unauthorized' })
    }

    const { event, data } = req.body as {
      event: string
      data?: {
        key?:     { id?: string; remoteJid?: string }
        message?: { conversation?: string; extendedTextMessage?: { text?: string } }
      }
    }

    if (event !== 'messages.upsert' || !data?.message) {
      return res.status(200).json({ ok: true })
    }

    const messageId = data.key?.id ?? ''
    const fromPhone = (data.key?.remoteJid ?? '').replace('@s.whatsapp.net', '')
    const body      = data.message.conversation ?? data.message.extendedTextMessage?.text ?? ''

    const existing = await prisma.onlinePayment.findFirst({
      where: { whatsappMessageId: messageId }
    })
    if (existing) return res.status(200).json({ ok: true, duplicate: true })

    const parsed = parseOrderMessage(body)
    if (!parsed) return res.status(200).json({ ok: true, ignored: true })

    const io = req.app.get('io') as SocketIOServer | null
    await createWhatsAppOrder(parsed, fromPhone, messageId, body, io)

    return res.status(200).json({ ok: true })

  } catch (err) {
    logger.error({ msg: 'Evolution webhook error', err })
    return res.status(200).json({ ok: true, error: String(err) })
  }
})

export default router
